version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=''
